- catppuccin-theme.el
The line number colors are at the moment set to a background color which makes them essentially invisible, as it is almost the same color as their background.
In this PR I have set them to the catppuccin foreground color so that they are visible. 😸
> change line number colors to catppuccin-comment color instead of background

- catppuccin-theme.el
Hello from hacktoberfest,
The domain you are referring to (shttps://spec.catppuccintheme.com/) is available to everyone to purchase and can be taken over by an attacker. An attacker could exploit such a situation by registering the expired/unpurchased domain and setting up a phishing page that mimics your project.
> Update catppuccin-theme.el - delete expired/unpurchased domain

- README.md
By default, the value of `custom-theme-directory` in Emacs is "~/.emacs.d". So if a user tried to run the code snippet in the documentation, he would be met with an error saying that "catppuccin" couldn't be loaded.
If we tell the user to install the theme to "~/.emacs.d/themes", then we should also tell him to set `custom-theme-directory` to that value.
> docs: mention that `custom-theme-directory` must be set

- catppuccin-theme.el
With the existing definition in place, loading web-mode fails. Since it's based on another face, use inherit.
> Fix invalid definition for web-mode-string-face

- catppuccin-theme.el
Adds internal functions `catppuccin-darken-color` and `catppuccin-lighten-color`
> Add darken and lighten operations and lighten ctp-current based on base

- catppuccin-theme.el
This PR adds [highlight-indent-guides](https://github.com/DarthFennec/highlight-indent-guides) face definitions. I tried to make it as close as https://github.com/catppuccin/nvim and I come up with `pink` for the active indent and `surface0` for the inactive ones. Suggestions welcome!
> feat: add highlight-indent-guides

- catppuccin-theme.el
This PR modifies `line-number-current-line` face so that the current line number has different color than others to make it consistent to https://github.com/catppuccin/nvim. Suggestions welcome!
Note: IMO it could be improved so that the current line number is left-aligned with 4 character space/template just as the neovim theme (neovim default I guess?), but I couldn't find the variable/function for this 😅
> feat: use distinct color for current line number

- catppuccin-theme.el
Request for comment as I'm not sure my taste matches the theme on this one.
The current version of show-paren-match is pretty subtle. Changing the background matches what ef-themes and modus-themes do to make the effect more obvious.
Here's what it looks like:
> Add background for paren match.

- catppuccin-theme.el
This adds support for [circe](https://github.com/emacs-circe/circe), and by extension lui.
> feat: circe and lui support

- catppuccin-theme.el
Adds a custom variable `catppuccin-italic-comments`, which is off by default to retain previous behavior. You can set it to `t` to have nice italic comments though.
Also set the comment-delimiter face to inherit from the comment face instead of shadow.
> [add] Allow user to have italic comments [i paid for them :(]

- catppuccin-theme.el
Regarding #98 .
This was also messing with my workflow :)
The way it is catppuccin is showing (only the variable show-trailing-whitespace set to t)
[left terminal / right GUI]
Applying a background the same color it was (warning):
And on whitespace-mode:
Problem is there's a color bump with the cursor and it becomes invisible
So according to https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md I peeked the peach color for this:
> feat: changes trailing-spaces face

- catppuccin-theme.el
Hi!
I saw the theme has `highlight-indent-guides` faces, I was tweaking with it and nothing happened.
Then I remember I dropped highlight-indent-guides in favor of the `indent-guide-mode`, it is simpler (only one face), but works with functions with blank lines (major problem with the cool `highlight-indent-guides`), like the first image.
Since it is only one line (the current level you're in), surface0 was a little bit too shady, almost difficult to see. I then set surface1 and tested on all variants. 
Mocha:
Macchiato:
Frappe:
Latte:
Do you think it's good?
> feat: customization for indent-guide-mode

- catppuccin-theme.el
This makes blockquotes italic by default, can be disabled by setting catppuccin-italic-blockquotes to `nil`
This also makes block quotes have a darker background to match other org blocks
Closes #101
> fix!(md-org): make blockquotes more consistent with other themes

- catppuccin-theme.el
Changed the builtin line-number face, linum face, solaire line-number face and the lsp-ui line-number face to inherit default, so as to propagate resizing through `C-x -/+` as expected.
> Fixed (hopefully) line-numbers not inheriting font scale

- catppuccin-theme.el
Hello again good people from Catppuccin! 
I use a cool package named `vc-msg` (https://github.com/redguardtoo/vc-msg), it uses `popup.el` (https://github.com/auto-complete/popup-el) to display tooltip messages with the git content regarding the current line.
It defaults to this style:
And I am proposing this:
Shouts to my typo on the screenshot, lol.
> feat: adds customization to popup.el tooltip

- catppuccin-theme.el
I'm a catppuccin newbie and I found myself forgetting two things:
1. The names of the different flavors
2. The "correct" way to change flavors
So I added this function to my personal helper functions to overcome those. I thought it might be helpful to others as well, which resulted in this PR.
This adds a convenience function (`catppuccin-load-flavor`) that allows the user to either pass a flavor directly to the function, or call it interactively and choose from a list of available flavors.
1. Call it directly and specify which flavor you want.
```emacs
(catppuccin-load-flavor 'latte)
```
2. Call it interactively and choose from the list of options.
```emacs
M-x catppuccin-load-flavor
```
https://github.com/catppuccin/emacs/assets/385726/93556ca2-4f06-4252-a1b8-07a099596b70
> feat: add a convenience function to load a new flavor

- catppuccin-theme.el
About `:inherit fringe`, I've been using it without any issues in [`nimbus-theme`](https://github.com/mrcnski/nimbus-theme) for some years. It just makes sure that the background matches the fringe background. Not relevant here, but in nimbus-theme it also makes sure that any other properties (like boldness) get cleared.
> Fix diff-hl faces

- README.md
This commit adds a hint to the README for doom emacs users.
Customizing the flavor of cattpuccin in doom emacs as suggested in the README:
```lisp
(load-theme 'catppuccin t t)
(setq catppuccin-flavor 'frappe) ;; or 'latte, 'macchiato, or 'mocha
(catppuccin-reload)
```
increases the startup time of doom emacs significantly (likely because catppuccin is loaded twice).
I noticed that setting the flavor before loading the theme:
```lisp
(setq catppuccin-flavor 'frappe) ;; or 'latte, 'macchiato, or 'mocha
(load-theme 'catppuccin t t)
```
works and so the call to `(catppuccin-reload)` can be omitted, yielding fast startup times again.
I added a respective hint for doom users to the README.
> docs: performance hint for doom emacs users

- catppuccin-theme.el
When `catppucin-get-color` is called interactively (via M-x or a
keybind) the color gets returned but not shown.
Call `message` on the result when called interactively.
>  fix: show color when catppuccin-get-color is called interactively 

- catppuccin-theme.el
Before/after (help-key-binding + info-menu-star):
Before/after (anzu):
> feat: support more faces

- catppuccin-theme.el
> fix: improve diff-mode highlighting

- .git-blame-ignore-revs
Commit hash got mangled in github's merge
> chore: update .git-blame-ignore-revs

- catppuccin-theme.el
```
catppuccin-theme.el:131:6: Warning: ‘beginning-of-buffer’ is for interactive
use only; use ‘(goto-char (point-min))’ instead.
catppuccin-theme.el:144:16: Warning: reference to free variable
‘catppuccin-flavor-alist’
In catppuccin-reload:
catppuccin-theme.el:192:2: Warning: docstring wider than 80 characters
In catppuccin-load-flavor:
catppuccin-theme.el:198:2: Warning: docstring wider than 80 characters catppuccin-theme.el:198:2: Warning: docstring has wrong usage of unescaped
single quotes (use \= or different quoting)
```
> chore: resolve byte-compile-file warnings

- catppuccin-theme.el
Adhere to Emacs naming conventions.
> refactor: rename catppuccin-get-color to catppuccin-color

- catppuccin-theme.el
Before/after:
Kind of weird in this picture since it's viewing a diff with unsolved git conflicts.
> feat: style smerge faces

- catppuccin-theme.el
The `catppuccin-definitions.el` file is currently loaded using the `find-file-noselect` function, which is inappropriate for the following reasons:
- It creates a file-visiting buffer that distracts the user and clutters their post-init Emacs state.
- It runs additional code to initialize buffer major mode and so on, which are unnecessary.
This PR fixes the code to use a temporary buffer to read the contents of `catppuccin-definitions.el` and pass the contents to the lisp reader, avoiding the aforementioned issues.
> fix: read catppuccin-definitions.el in temp buffer instead of visiting

- catppuccin-theme.el
> feat: style compilation-mode-line faces

- catppuccin-theme.el
I chose to color the foreground rather than the background since I think that looks cleaner, but I'm open to either :slightly_smiling_face:.
> feat: color org-mode-line-clock-overrun

- catppuccin-theme.el
(before `markdown-mode` is loaded)
`markdown-mode` may not be loaded by the time Org is used, which results in the
`org-quote` face being unstyled since `markdown-blockquote-face` is not yet defined.
I also took the opportunity to remove a seemingly-duplicate entry for `markdown-blockquote-face` :shrug:.
Probably fixes #123
> Copy `markdown-blockquote-face` definition to `org-quote`

- catppuccin-theme.el
> fix: improve diff-hl gutter readability

- catppuccin-theme.el
`yellow1` is the default background color for the `evil-search-highlight-persist-highlight-face`.  The same settings as for `lazy-highlight` seem appropriate.
> Fixed `yellow1` background color for evil-isearch

- catppuccin-theme.el
Updates the smerge faces to use unspecified rather than nil to avoid warnings in the emacs message buffer
> fix: use unspecified over nil in smerge faces

- catppuccin-theme.el
See: https://github.com/catppuccin/emacs/issues/189
Not all major modes use this face, but, as shown in the example above, at least json-ts-mode does.
EDIT: well, it uses font-lock-property-use-face, but that one inherits from font-lock-property-name-face
> feat: style font-lock-property-name-face

- catppuccin-theme.el
Currently, the in-buffer faces for Flymake aren't customized. This makes them incosistent with the ones used for echo messages, i.e. `flymake-note-echo`, since it inherits from `compilation-info`, which in turn inherits from `success`.
For more details, see #203
I can close this PR is this was an intentional design decision.
Closes #203
> feat: style flymake faces

- catppuccin-theme.el
I've made those resemble the faces used in markdown-mode.
It's a hot mess...
Can't get a proper screenshot without restarting Emacs and I do this very rarely. 😅
> Add adoc-mode faces

- catppuccin-theme.el
After using the colors for a bit I've identified a few small improvements and now they look better IMO (and are more consistent with Markdown)
> Update adoc faces

- catppuccin-theme.el
> chore: remove catppuccin-enlarge-headings

- catppuccin-theme.el
Fixed #128 "Italics shown as underlined in doom emacs 29 pgtk"
> fix: Italics shown as underlined

- catppuccin-theme.el
- Update faces: `company-preview`, `company-preview-search`, `company-tooltip-search`, `company-tooltip-search-selection`
- Remove obsolete faces: `company-scrollbar-bg` and `company-scrollbar-fg`
- Remove TODO
> Define faces for company

- catppuccin-theme.el
[eglot-supplements](https://codeberg.org/harald/eglot-supplements) is a package that additional Language Server Protocol specifications to Eglot.
Most of the faces there are implemented using ~inheritage~ inheritance, except for these two I added to the commit.
<details>
</details>
<details>
</details>
> Add eglot-supplements faces

- catppuccin-theme.el
Most of the faces in `completion-preview` already look good with Catppuccin (due to ~inheritage~ inheritance), except for this one.
<details>
</details>
<details>
</details>
Maybe making it inherit from `match` makes more sense? Here is the look:
<details>
</details>
Let me know what you think. From a first impression I kind of like it, but maybe it could get annoying after some time.
> feat: style completion-preview-exact

- catppuccin-theme.el
Corrected powerline active colors by swapping foreground and background values for better visibility.
Fixed #226
> Emacs Catppuccin theme powerline foreground/background

- catppuccin-theme.el
---
Add a `defcustom` to make line numbers darker by using the `mantle` color rather than the `base` color.  Only `linum` and `line-number` has been changed; mode specific line number faces were all already using something other than the base color.
This is a personal preference of mine, so I thought I'd add it as an option.  I've left the default to be `nil`, so there is no change in default behavior.
> Option for darker line numbers
